### ISSUE TITLE
Event List

### ISSUE THREAD

**Issue by bcollin** [mibuthu/wp-event-list#152]
Since you appear to have become completely mute on your other projects, but are still active on this one, I am going to post my question here. 

Are you ever going to work on the Event List plugin again? Or are you going to let it die a slow death?

**Comment by mibuthu** [comment]
I will work on it again, when I have updated my comment-guestbook plugin.

**Comment by bcollin** [comment]
The plug-in's page on wordpress.org is now displaying the following message: 

"This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."

**Comment by JosKlever** [comment]
Hi @mibuthu, it's been 2 years since the last update and although I think that the plugin is still working, I'm getting notifications about the fact this plugin might be abandoned. So it would be great if you could release an update, even if it doesn't containing new functionality. Just to show it's still working and existing and new users know they can still use this plugin. Thanks!

**Comment by mibuthu** [comment]
Updated released
